package mythic

var MythicForensicArtifacts = map[string]string{
	"event_4688": "Windows Security: Process creation - Apollo/Poseidon/Athena agent execution",
	"sysmon_1": "Sysmon: Process creation - agent payload execution",
	"sysmon_8": "Sysmon: CreateRemoteThread - agent injection into target process",
	"sysmon_10": "Sysmon: ProcessAccess - agent memory access for task injection",
	"sysmon_11": "Sysmon: FileCreate - agent payload dropped to disk",
	"sysmon_15": "Sysmon: FileCreateStreamHash - agent via alternate data stream",
	"sysmon_22": "Sysmon: DNSEvent - agent DNS C2 queries",
	"sysmon_25": "Sysmon: ProcessTampering - agent process hollowing",
	"network_ja3": "JA3: Default Mythic Apollo/Poseidon HTTPS client fingerprint",
	"network_ws": "WebSocket: /ws - Mythic WebSocket real-time communication",
	"network_jwt": "JWT Authorization header in Mythic REST API calls",
	"network_uri_api": "URI: /api/v1.4/ - Mythic REST API endpoints",
	"network_ua": "User-Agent: Mythic agent default HTTP client headers",
	"network_c2_https": "HTTPS C2 traffic with Mythic-specific beacon interval patterns",
	"file_agent_exe": "agent.exe / apollo.exe / poseidon.exe - Mythic agent payloads",
	"file_temp_dll": "%TEMP%\\*.tmp - Agent DLL dropped during execution",
	"process_apollo": "apollo.exe - Apollo (.NET) agent process",
	"process_poseidon": "poseidon.exe - Poseidon (Go) agent process",
	"process_athena": "athena.exe - Athena (.NET) agent process",
	"process_merlin": "merlin.exe - Merlin (Go) agent process",
	"memory_dotnet": ".NET CLR loaded in process memory - Apollo/Athena agent",
	"memory_go": "Go runtime loaded in process memory - Poseidon/Merlin agent",
	"memory_rwx": "RWX memory region - Agent shellcode in private memory",
	"memory_reflective": "Reflective DLL loading pattern - Agent injected into memory",
	"detection_etw": "ETW events from .NET runtime - Apollo/Athena agent activity",
	"detection_amsi": "AMSI scan events on PowerShell agent commands",
	"detection_c2_timing": "C2 beacon timing analysis - agent check-in pattern detection",
	"detection_websocket": "WebSocket connection to Mythic server",
	"detection_rest_api": "REST API calls to Mythic server with JWT auth",
}
