package cobaltstrike

var CobaltStrikeForensicArtifacts = map[string]string{
	"event_4688": "Windows Security: Process creation - beacon payload",
	"event_5156": "Windows Security: WFP connection - beacon C2 outbound",
	"event_5158": "Windows Security: WFP bind - beacon listener",
	"sysmon_1": "Sysmon: Process creation - artifact.exe, beacon.exe execution",
	"sysmon_8": "Sysmon: CreateRemoteThread - beacon injection",
	"sysmon_10": "Sysmon: ProcessAccess - beacon memory access",
	"sysmon_11": "Sysmon: FileCreate - beacon DLL dropped to disk",
	"sysmon_12": "Sysmon: RegistryEvent - Run key persistence",
	"sysmon_13": "Sysmon: RegistryEvent - service persistence",
	"sysmon_15": "Sysmon: FileCreateStreamHash - alternate data stream",
	"sysmon_22": "Sysmon: DNSEvent - beacon DNS queries",
	"sysmon_25": "Sysmon: ProcessTampering - beacon process hollowing",
	"network_ja3": "JA3: 72a589da5862efb0b91c7e4f7e3d3e4f - Default CS HTTPS client",
	"network_uri_pixel": "URI: /pixel.gif - Common CS beacon callback URI",
	"network_uri_utm": "URI: /__utm.gif - Common CS beacon callback URI",
	"network_uri_jquery": "URI: /jquery-3.3.1.min.js - Common CS staging URI",
	"network_ua_msie": "User-Agent: Mozilla/5.0 (compatible; MSIE 10.0...) - Default CS beacon",
	"network_dns_stage": "DNS: *.stage.* - CS DNS staging domain pattern",
	"registry_run_hklm": "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run - AdobeUpdater",
	"registry_run_hkcu": "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run - JavaUpdate",
	"registry_service": "HKLM\\SYSTEM\\CurrentControlSet\\Services - CS service persistence",
	"file_temp_dll": "%TEMP%\\*.tmp / %TEMP%\\beacon*.dll - Beacon DLL dropped to temp",
	"file_appdata_dll": "%APPDATA%\\Microsoft\\*.dll - Beacon masquerading as MS DLL",
	"file_artifact_exe": "artifact.exe - CS artifact payload",
	"file_beacon_exe": "beacon.exe - CS beacon payload",
	"process_beacon": "beacon.exe, artifact.exe - CS beacon processes",
	"process_rundll32": "rundll32.exe - CS beacon loaded via rundll32",
	"process_regsvr32": "regsvr32.exe - CS beacon via regsvr32",
	"process_mshta": "mshta.exe - CS beacon via mshta",
	"process_powershell": "powershell.exe - CS beacon PowerShell stager",
	"process_wmic": "wmic.exe - CS beacon via WMIC",
	"pipe_msagent": "\\\\.\\pipe\\msagent_* - CS SMB named pipe",
	"pipe_status": "\\\\.\\pipe\\status_* - CS SMB named pipe",
	"memory_reflective_dll": "MZ header in non-image memory - Beacon DLL reflectively loaded",
	"memory_rwx": "RWX memory region - Beacon shellcode in private memory",
	"memory_hollowing": "Process hollowing - Beacon injected into legitimate process",
	"detection_ja3": "Malleable C2 profile detection via JA3 fingerprinting",
	"detection_timing": "Beacon timing analysis - jitter pattern detection",
	"detection_dns": "DNS query pattern analysis - TXT record exfil",
	"detection_named_pipe": "Named pipe creation on SMB beacon targets",
	"detection_sysmon_8": "Sysmon EventID 8 (CreateRemoteThread) for beacon injection",
}
