package ticketing

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/ares/engine/internal/logger"
)

type PRResult struct {
	ProviderID string `json:"provider_id"`
	ScanID     string `json:"scan_id"`
	FindingID  string `json:"finding_id"`
	Status     string `json:"status"`
	URL        string `json:"url,omitempty"`
	Number     int    `json:"number,omitempty"`
	Error      string `json:"error,omitempty"`
}

func detectLanguage(filename string) string {
	ext := strings.ToLower(filename[strings.LastIndex(filename, ".")+1:])
	switch ext {
	case "go":
		return "go"
	case "js", "jsx", "ts", "tsx":
		return "javascript"
	case "py":
		return "python"
	case "java":
		return "java"
	case "rb":
		return "ruby"
	case "php":
		return "php"
	case "cs":
		return "csharp"
	case "rs":
		return "rust"
	default:
		return "unknown"
	}
}

func (tm *TicketManager) CreateRemediationPR(scanID string, targetURL string, finding FindingInfo, fixedCode string, fileName string) *PRResult {
	tm.mu.RLock()
	defer tm.mu.RUnlock()
	for id, cfg := range tm.providers {
		if !cfg.Enabled {
			continue
		}
		if cfg.Provider != ProviderGitHub {
			continue
		}
		if cfg.Owner == "" || cfg.Repo == "" {
			continue
		}
		branchName := fmt.Sprintf("ares-remediation/%s-%s", finding.Type, finding.ID)
		title := fmt.Sprintf("[ARES Remediation] %s - %s", finding.Severity, finding.Title)
		body := fmt.Sprintf("## Automated Remediation\n\n**Vulnerability:** %s\n**Severity:** %s\n**CVSS:** %.1f\n\n### Description\n%s\n\n### Fix\n```\n%s\n```\n\n---\n*This PR was automatically generated by ARES PTaaS*",
			finding.Title, finding.Severity, finding.CVSS, finding.Description, fixedCode)
		apiURL := fmt.Sprintf("https://api.github.com/repos/%s/%s/pulls", cfg.Owner, cfg.Repo)
		payload := map[string]interface{}{
			"title": title,
			"body":  body,
			"head":  branchName,
			"base":  "main",
		}
		data, _ := json.Marshal(payload)
		req, err := http.NewRequest("POST", apiURL, bytes.NewReader(data))
		if err != nil {
			return nil
		}
		req.Header.Set("Content-Type", "application/json")
		req.Header.Set("Authorization", "Bearer "+cfg.Token)
		resp, err := httpClient.Do(req)
		if err != nil {
			return nil
		}
		defer resp.Body.Close()
		if resp.StatusCode >= 300 {
			return nil
		}
		var result struct {
			HTMLURL string `json:"html_url"`
			Number  int    `json:"number"`
		}
		if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
			return nil
		}
		return &PRResult{ProviderID: id, ScanID: scanID, FindingID: finding.ID, Status: "open", URL: result.HTMLURL, Number: result.Number}
	}
	return nil
}

func (tm *TicketManager) GenerateAndApplyRemediation(scanID string, targetURL string, finding FindingInfo, fileName string) *PRResult {
	lang := detectLanguage(fileName)
	fixedCode := fmt.Sprintf("// Automated fix for %s (%s)\n// Language: %s\n// Original: %s", finding.ID, finding.Title, lang, targetURL)
	return tm.CreateRemediationPR(scanID, targetURL, finding, fixedCode, fileName)
}

var httpClient = &http.Client{Timeout: 30 * time.Second}

func sanitizeTicketContent(s string) string {
	s = strings.ReplaceAll(s, "\x00", "")
	s = strings.Map(func(r rune) rune {
		if r == '\n' || r == '\r' || r == '\t' || (r >= 32 && r <= 126) {
			return r
		}
		if r > 126 {
			return r
		}
		return -1
	}, s)
	if len(s) > 4000 {
		s = s[:4000]
	}
	return strings.TrimSpace(s)
}

type Provider string

const (
	ProviderJira       Provider = "jira"
	ProviderGitHub     Provider = "github"
	ProviderServiceNow Provider = "servicenow"
	ProviderLinear     Provider = "linear"
)

type TicketConfig struct {
	Provider  Provider `json:"provider"`
	URL       string   `json:"url"`
	Token     string   `json:"-"`
	Email     string   `json:"email,omitempty"`
	Project   string   `json:"project"`
	Enabled   bool     `json:"enabled"`
	Assignees []string `json:"assignees,omitempty"`
	Owner     string   `json:"owner,omitempty"`
	Repo      string   `json:"repo,omitempty"`
	Labels    []string `json:"labels,omitempty"`
	Username  string   `json:"username,omitempty"`
	Password  string   `json:"-"`
	Assignee  string   `json:"assignee,omitempty"`
	TeamID    string   `json:"team_id,omitempty"`
}

type TicketManager struct {
	mu        sync.RWMutex
	providers map[string]*TicketConfig
}

func NewTicketManager() *TicketManager {
	return &TicketManager{
		providers: make(map[string]*TicketConfig),
	}
}

func (tm *TicketManager) ListProviders() map[string]*TicketConfig {
	tm.mu.RLock()
	defer tm.mu.RUnlock()
	result := make(map[string]*TicketConfig, len(tm.providers))
	for k, v := range tm.providers {
		cp := *v
		cp.Token = ""
		cp.Password = ""
		result[k] = &cp
	}
	return result
}

func (tm *TicketManager) GetProvider(id string) *TicketConfig {
	tm.mu.RLock()
	defer tm.mu.RUnlock()
	return tm.providers[id]
}

func (tm *TicketManager) RemoveProvider(id string) {
	tm.mu.Lock()
	defer tm.mu.Unlock()
	delete(tm.providers, id)
}

func (tm *TicketManager) TestConnection(id string) error {
	tm.mu.RLock()
	cfg, ok := tm.providers[id]
	tm.mu.RUnlock()
	if !ok {
		return fmt.Errorf("provider %q not found", id)
	}
	switch cfg.Provider {
	case ProviderGitHub:
		req, err := http.NewRequest("GET", "https://api.github.com/user", nil)
		if err != nil {
			return fmt.Errorf("failed to create request: %w", err)
		}
		req.Header.Set("Authorization", "Bearer "+cfg.Token)
		resp, err := httpClient.Do(req)
		if err != nil {
			return fmt.Errorf("connection failed: %w", err)
		}
		resp.Body.Close()
		if resp.StatusCode >= 300 {
			return fmt.Errorf("API returned status %d", resp.StatusCode)
		}
		return nil
	case ProviderJira:
		req, err := http.NewRequest("GET", strings.TrimRight(cfg.URL, "/")+"/rest/api/3/project", nil)
		if err != nil {
			return fmt.Errorf("failed to create request: %w", err)
		}
		if cfg.Email != "" && cfg.Token != "" {
			auth := base64.StdEncoding.EncodeToString([]byte(cfg.Email + ":" + cfg.Token))
			req.Header.Set("Authorization", "Basic "+auth)
		} else if cfg.Token != "" {
			req.Header.Set("Authorization", "Bearer "+cfg.Token)
		}
		resp, err := httpClient.Do(req)
		if err != nil {
			return fmt.Errorf("connection failed: %w", err)
		}
		resp.Body.Close()
		if resp.StatusCode >= 300 {
			return fmt.Errorf("API returned status %d", resp.StatusCode)
		}
		return nil
	default:
		req, err := http.NewRequest("GET", cfg.URL, nil)
		if err != nil {
			return fmt.Errorf("failed to create request: %w", err)
		}
		resp, err := httpClient.Do(req)
		if err != nil {
			return fmt.Errorf("connection failed: %w", err)
		}
		resp.Body.Close()
		return nil
	}
}

func (tm *TicketManager) AddProvider(id string, cfg *TicketConfig) {
	tm.mu.Lock()
	defer tm.mu.Unlock()
	tm.providers[id] = cfg
}

func severityToPriority(severity string) string {
	switch strings.ToLower(severity) {
	case "critical":
		return "Highest"
	case "high":
		return "High"
	case "medium":
		return "Medium"
	case "low":
		return "Low"
	default:
		return "Lowest"
	}
}

type FindingInfo struct {
	ID          string
	Title       string
	Severity    string
	Target      string
	Description string
	Evidence    map[string]string
	CVSS        float64
	Type        string
}

func (tm *TicketManager) CreateFindingTicket(scanID, target string, finding FindingInfo) {
	tm.mu.RLock()
	defer tm.mu.RUnlock()

	for id, cfg := range tm.providers {
		if !cfg.Enabled {
			continue
		}
		switch cfg.Provider {
		case ProviderJira:
			tm.createJiraTicket(id, cfg, scanID, target, finding)
		case ProviderGitHub:
			tm.createGitHubIssue(id, cfg, scanID, target, finding)
		case ProviderServiceNow:
			tm.createServiceNowTicket(id, cfg, scanID, target, finding)
		case ProviderLinear:
			tm.createLinearIssue(id, cfg, scanID, target, finding)
		}
	}
}

func (tm *TicketManager) createJiraTicket(id string, cfg *TicketConfig, scanID, target string, finding FindingInfo) {
	sanitizedTitle := sanitizeTicketContent(finding.Title)
	sanitizedDesc := sanitizeTicketContent(finding.Description)
	sanitizedType := sanitizeTicketContent(finding.Type)
	desc := fmt.Sprintf("ARES Scan: %s\nTarget: %s\nScan ID: %s\n\nDescription:\n%s\n\nCVSS: %.1f\nFinding Type: %s",
		sanitizedTitle, target, scanID, sanitizedDesc, finding.CVSS, sanitizedType)

	priority := severityToPriority(finding.Severity)

	body := map[string]interface{}{
		"fields": map[string]interface{}{
			"project": map[string]string{
				"key": cfg.Project,
			},
			"summary":     fmt.Sprintf("[ARES] %s - %s", finding.Severity, sanitizedTitle),
			"description": desc,
			"issuetype": map[string]string{
				"name": "Bug",
			},
			"priority": map[string]string{
				"name": priority,
			},
			"customfield_securityteam": sanitizedType,
			"customfield_cvss":         finding.CVSS,
		},
	}

	data, err := json.Marshal(body)
	if err != nil {
		logger.Error("Failed to marshal Jira request body", logger.Fields{"component": "Ticketing", "provider_id": id, "error": err})
		return
	}
	req, err := http.NewRequest("POST", strings.TrimRight(cfg.URL, "/")+"/rest/api/3/issue", bytes.NewReader(data))
	if err != nil {
		logger.Error("Failed to create Jira request", logger.Fields{"component": "Ticketing", "provider_id": id, "error": err})
		return
	}
	req.Header.Set("Content-Type", "application/json")
	if cfg.Email != "" && cfg.Token != "" {
		auth := base64.StdEncoding.EncodeToString([]byte(cfg.Email + ":" + cfg.Token))
		req.Header.Set("Authorization", "Basic "+auth)
	} else if cfg.Token != "" {
		req.Header.Set("Authorization", "Bearer "+cfg.Token)
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		logger.Error("Jira API call failed", logger.Fields{"component": "Ticketing", "provider_id": id, "error": err})
		return
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		respBody, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
		if err != nil {
			logger.Warn("Jira API returned error, failed to read response", logger.Fields{"component": "Ticketing", "provider_id": id, "status_code": resp.StatusCode, "error": err})
			return
		}
		logger.Warn("Jira API returned error", logger.Fields{"component": "Ticketing", "provider_id": id, "status_code": resp.StatusCode, "response": string(respBody)})
		return
	}

	logger.Info("Jira ticket created for finding", logger.Fields{"component": "Ticketing", "provider_id": id, "finding_id": finding.ID})
}

func (tm *TicketManager) createGitHubIssue(id string, cfg *TicketConfig, scanID, target string, finding FindingInfo) {
	owner := cfg.Owner
	repo := cfg.Repo
	if owner == "" || repo == "" {
		logger.Warn("GitHub: owner and repo required", logger.Fields{"component": "Ticketing", "provider_id": id})
		return
	}

	sanitizedTitle := sanitizeTicketContent(finding.Title)
	sanitizedDesc := sanitizeTicketContent(finding.Description)
	labels := []string{"bug", "security"}
	labels = append(labels, finding.Severity)
	labels = append(labels, cfg.Labels...)

	body := map[string]interface{}{
		"title": fmt.Sprintf("[ARES] %s - %s", finding.Severity, sanitizedTitle),
		"body": fmt.Sprintf("## Vulnerability Report\n\n**Scan ID:** %s\n**Target:** %s\n**Severity:** %s\n**CVSS:** %.1f\n**Type:** %s\n\n### Description\n%s\n\n### Evidence\n```\n%v\n```",
			scanID, target, finding.Severity, finding.CVSS, sanitizeTicketContent(finding.Type), sanitizedDesc, finding.Evidence),
		"labels": labels,
	}

	if len(cfg.Assignees) > 0 {
		body["assignees"] = cfg.Assignees
	}

	data, err := json.Marshal(body)
	if err != nil {
		logger.Error("Failed to marshal GitHub request body", logger.Fields{"component": "Ticketing", "provider_id": id, "error": err})
		return
	}
	apiURL := fmt.Sprintf("https://api.github.com/repos/%s/%s/issues", owner, repo)
	req, err := http.NewRequest("POST", apiURL, bytes.NewReader(data))
	if err != nil {
		logger.Error("Failed to create GitHub request", logger.Fields{"component": "Ticketing", "provider_id": id, "error": err})
		return
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+cfg.Token)
	req.Header.Set("Accept", "application/vnd.github.v3+json")

	resp, err := httpClient.Do(req)
	if err != nil {
		logger.Error("GitHub API call failed", logger.Fields{"component": "Ticketing", "provider_id": id, "error": err})
		return
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		respBody, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
		if err != nil {
			logger.Warn("GitHub API returned error, failed to read response", logger.Fields{"component": "Ticketing", "provider_id": id, "status_code": resp.StatusCode, "error": err})
			return
		}
		logger.Warn("GitHub API returned error", logger.Fields{"component": "Ticketing", "provider_id": id, "status_code": resp.StatusCode, "response": string(respBody)})
		return
	}

	logger.Info("GitHub issue created for finding", logger.Fields{"component": "Ticketing", "provider_id": id, "finding_id": finding.ID})
}
